"""Prepare NEB endpoint structures from QE-relaxed geometries (Task 8).

Writes XYZ files for the two ferrocene conformer endpoints:
  A: eclipsed D5h  (primary ferrocene,                  ΔE = 0 meV)
  B: staggered D5d (ferrocene__ring2_rotation_deg__+36,  ΔE = 41.68 meV)

These are validated QE-relaxed geometries at PBE/60 Ry. They serve as NEB
endpoints for a ferrocene conformer-rotation path demo with the nebwalk package.

Reads:
  data/processed/full_dataset_v0.2.csv

Writes:
  structures/neb_endpoints/ferrocene_eclipsed_d5h.xyz
  structures/neb_endpoints/ferrocene_staggered_d5d.xyz
  structures/neb_endpoints/README.md
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import PROJECT_ROOT, setup_logger  # noqa: E402

logger = setup_logger("prepare_neb_endpoints", "neb_endpoints.log")

ENDPOINT_A_ID = "ferrocene"
ENDPOINT_B_ID = "ferrocene__ring2_rotation_deg__+36"
DATASET_CSV = PROJECT_ROOT / "data" / "processed" / "full_dataset_v0.2.csv"
OUT_DIR = PROJECT_ROOT / "structures" / "neb_endpoints"

RY_TO_EV = 13.605693122994


def _read_row(rows: dict[str, dict], system_id: str) -> dict:
    row = rows.get(system_id)
    if row is None:
        raise ValueError(f"system_id '{system_id}' not found in dataset")
    if row.get("convergence_status") != "converged":
        raise ValueError(
            f"{system_id}: convergence_status='{row['convergence_status']}' — "
            "cannot use unconverged structure as NEB endpoint"
        )
    if not row.get("final_positions_angstrom"):
        raise ValueError(f"{system_id}: no final_positions_angstrom in dataset")
    return row


def positions_to_xyz_lines(pos_list: list[dict]) -> list[str]:
    return [f"{p['symbol']:2s}  {p['x']:12.6f}  {p['y']:12.6f}  {p['z']:12.6f}"
            for p in pos_list]


def write_xyz(path: Path, pos_list: list[dict], comment: str) -> None:
    n = len(pos_list)
    lines = [str(n), comment] + positions_to_xyz_lines(pos_list)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("Wrote %s (%d atoms)", path, n)


def write_readme(out_dir: Path, a_row: dict, b_row: dict,
                 delta_e_mev: float) -> None:
    text = f"""# NEB Endpoints — Ferrocene Conformer Rotation

Generated by `scripts/17_prepare_neb_endpoints.py`. Do not edit by hand.

## Physical system

Ferrocene Fe(C5H5)2 conformer rotation: eclipsed D5h → staggered D5d.
The two Cp rings rotate by 36° relative to each other (half of 72°, the
5-fold periodicity), going from fully eclipsed to fully staggered.

## Computational details

- Calculator: Quantum ESPRESSO pw.x v7.4.1
- Functional: PBE (no dispersion)
- ecutwfc: 60 Ry  (Fe PAW-031; note: 90 Ry recommended from Task 1.5)
- ecutrho: 480 Ry
- assume_isolated: mt (Martyna-Tuckerman)
- Convergence: BFGS, forc_conv_thr=0.0001 Ry/bohr, etot_conv_thr=1e-5 Ry
- Source: `data/processed/full_dataset_v0.2.csv`

## Endpoint files

| File | system_id | Conformer | ΔE (meV) |
|------|-----------|-----------|---------|
| `ferrocene_eclipsed_d5h.xyz`  | {ENDPOINT_A_ID} | eclipsed D5h  | 0.0 |
| `ferrocene_staggered_d5d.xyz` | {ENDPOINT_B_ID} | staggered D5d | {delta_e_mev:.2f} |

The ΔE={delta_e_mev:.2f} meV agrees with the experimental eclipsed–staggered
barrier (~4 kJ/mol ≈ 41 meV, Haaland & Nilsson 1968).

## Known limitations

- Both structures use PBE/60 Ry. The recommended cutoff for Fe is 90 Ry
  (Task 1.5). Bond-length accuracy is within ~0.02 Å of experiment, which
  is sufficient for NEB endpoint input, but be aware that energetics may
  shift slightly at the recommended cutoff.
- No dispersion correction (PBE-D3 conformer check was done separately in
  Task 2 at 90 Ry; that calculation confirmed eclipsed D5h as ground state).
- These are single-point NEB endpoints. Actual NEB path images should be
  generated by interpolation (e.g., nebwalk linear/IDPP interpolation).

## Usage with nebwalk

```python
from ase.io import read
images_0 = read('structures/neb_endpoints/ferrocene_eclipsed_d5h.xyz')
images_1 = read('structures/neb_endpoints/ferrocene_staggered_d5d.xyz')
# Then feed to nebwalk NEB builder
```
"""
    (out_dir / "README.md").write_text(text, encoding="utf-8")
    logger.info("Wrote %s/README.md", out_dir)


def main() -> None:
    if not DATASET_CSV.exists():
        logger.error("Dataset not found: %s", DATASET_CSV)
        sys.exit(1)

    with DATASET_CSV.open(encoding="utf-8") as f:
        all_rows = {r["system_id"]: r for r in csv.DictReader(f)}

    a_row = _read_row(all_rows, ENDPOINT_A_ID)
    b_row = _read_row(all_rows, ENDPOINT_B_ID)

    pos_a = json.loads(a_row["final_positions_angstrom"])
    pos_b = json.loads(b_row["final_positions_angstrom"])

    if len(pos_a) != len(pos_b):
        logger.error(
            "Atom count mismatch: %s has %d atoms, %s has %d",
            ENDPOINT_A_ID, len(pos_a), ENDPOINT_B_ID, len(pos_b)
        )
        sys.exit(1)

    e_a = float(a_row["final_energy_ry"]) * RY_TO_EV
    e_b = float(b_row["final_energy_ry"]) * RY_TO_EV
    delta_e_ev = e_b - e_a
    delta_e_mev = delta_e_ev * 1000

    logger.info("Endpoint A: %s  E=%.6f eV", ENDPOINT_A_ID, e_a)
    logger.info("Endpoint B: %s  E=%.6f eV  ΔE=%.2f meV", ENDPOINT_B_ID, e_b, delta_e_mev)

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    write_xyz(
        OUT_DIR / "ferrocene_eclipsed_d5h.xyz",
        pos_a,
        f"ferrocene eclipsed D5h  PBE/60 Ry  E={e_a:.6f} eV  source={ENDPOINT_A_ID}"
    )
    write_xyz(
        OUT_DIR / "ferrocene_staggered_d5d.xyz",
        pos_b,
        (f"ferrocene staggered D5d  PBE/60 Ry  E={e_b:.6f} eV  "
         f"dE={delta_e_mev:.2f} meV vs eclipsed  source={ENDPOINT_B_ID}")
    )
    write_readme(OUT_DIR, a_row, b_row, delta_e_mev)

    logger.info("=== Task 8 complete: NEB endpoints written to %s ===", OUT_DIR)


if __name__ == "__main__":
    main()
